[package]
name = "custom-tycho"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tracing-subscriber = "0.3"

tycho-client = "0.125.2"
tycho-common = "0.125.2"
tycho-core = "0.3.5"
tycho-simulation = "0.226.1"
